### ISSUE TITLE
Characters doesn't show up in any way

### ISSUE THREAD

**Issue by WindowsFan2006** [ctrlcctrlv/FRBCistercian#1]
I installed the font, but there's no glyphs and it shows up just boxes instead of the numerals. I tried logging out and log on to fix this problem, but it couldn't. Can you fix it?

**Comment by WindowsFan2006** [comment]
I mean the private use chars shows up as white boxes.

**Comment by ctrlcctrlv** [comment]
The font doesn't work w/normal numerals. This doesn't show? 􀀂􀀃􀀄􀀅

It must be the application or the environment.
